### PR TITLE
Tests for raster module

### PR DESCRIPTION
**Pull request by kysolvik**
Working on adding tests for the raster module (#32). Will update when finished

### CODE REVIEW

**Comment by kysolvik** [comment]
Build failed because I forgot to activate pre-commit hook/run black. Will fix!

**Comment by kysolvik** [comment]
Hi @lwasser,

This PR is ready for review but no rush. I'll start working on the base module tests in the meantime. Thanks!!

**Comment by lwasser** [comment]
awesome thank you @kysolvik i ran out of time today but i'll be sure to review this when i'm back next week!!!

**Comment by kysolvik** [comment]
Probably going to fail appveyor because of the pip problem, will update once #47 is merged

**Review by lwasser — APPROVED** [review]
Thank you @kysolvik  this all looks good!!

**Pull request merged**
