### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nkorinek**
Updating dependencies to be the most recent versions of the tool.

### CODE REVIEW

**Comment by lwasser** [comment]
@nkorinek it looks like this is failing because of the pre-commit version bump. what i suggest is that you
1. try to remove that update here and if everythign passes we can merge what is passing. 
2. leave the pre-commit broken pr from the bot open as well and we can look into this issue in the future - perhaps add an issue on it. that way we can update everything else, close associated other pr's and come back to this one update later.

**Comment by nkorinek** [comment]
@lwasser just fyi I was looking at this pr again and it seems like the appveyor ran into an issue and needs to be re-run. I tried to do it but I either don't have the permissions or am not seeing the button

**Comment by nkorinek** [comment]
@lwasser reverted pip here and it fixed the pr, ready to merge!

**Comment by lwasser** [comment]
@nkorinek great. PIP upgrades have been consistently problematic so i've mostly closed those PR's :) thank you for this. merging

**Pull request merged**
