### PR TITLE
Assert string accept spaces

### PR DESCRIPTION
**Pull request by nkorinek**
Made it so that `assert_string_contains()` accepts correct strings with spaces in them, as well as added tests to make sure it works.

### CODE REVIEW

**Comment by lwasser** [comment]
@nkorinek for all of thse pr's can you link to the relevant issue so i can better understand what they address? also is this used in a vignette? maybe we can add it to a vignette

**Comment by nkorinek** [comment]
@lwasser not sure how to add this to a vignette, it's more a bug fix than new functionality. I could modify the existing vignette on checking titles/axis labels to include key words with spaces if you want, but that's all I could think to do.

**Comment by nkorinek** [comment]
@lwasser this is only failing bc it says code coverage went down, which I don't believe it did...should be ok to merge!

**Comment by lwasser** [comment]
this looks good @nkorinek i will merge it now - thank you!!

**Pull request merged**
