### PR TITLE
Add flake8 fix

### PR DESCRIPTION
**Pull request by nkorinek**
Resolving merge conflicts (hopefully)

### CODE REVIEW

**Comment by nkorinek** [comment]
@lwasser this is finally passing Travis! It's still failing Codacy (would you like me to fix that? It's just failing some section titles it thinks are mis-placed) but aside from that it's looking good!

**Comment by nkorinek** [comment]
Codacy failing due to header's triggering the `String statement has no effect` error, which I believe is soon to be fixed/has already been fixed, correct? If not, it should be fixed soon or the way we handle headers should change.

AppVeyor is failing due to an environment issue it looks like. The error message is 

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib >=3.0.0
  - rasterio
```

Unsure how to fix this one!

**Comment by lwasser** [comment]
@nkorinek ahhhh there were some issues last week with things not resolving correctly. let me try to rerun appveyor today
codacy i'm not sure what is going on!

**Comment by lwasser** [comment]
@nkorinek i see what is going on with codacy. it doesn't like the `"""section here"""` i just posted on slack about this but if you have a bit of time could you look into best practices here? i like breaking up the code but maybe we want to just use a single comment? altho i don't know if codacy will like that either. CI is rerunning.

**Pull request merged**
