### PR TITLE
Adding Histogram Vignette

### PR DESCRIPTION
**Pull request by marty-larocque**
This adds a vignette that demonstrates how to test histograms, addressing issue #149.

### CODE REVIEW

**Comment by ryla5068** [comment]
For reference, here is a pdf of the vignette.
[Testing Histograms — matplotcheck 0.1.0 documentation.pdf](https://github.com/earthlab/matplotcheck/files/3923538/Testing.Histograms.matplotcheck.0.1.0.documentation.pdf)

**Comment by marty-larocque** [comment]
For reference, here is a pdf of the vignette.
[Testing Histograms — matplotcheck 0.1.0 documentation.pdf](https://github.com/earthlab/matplotcheck/files/3923776/Testing.Histograms.matplotcheck.0.1.0.documentation.pdf)

**Comment by lwasser** [comment]
thank you @ryla5068 it would be nice at the end of the vignette to demonstrate that you can use the basic assert statements to test for x and y axis labels and titles too. will you please add that to the vignette? i'm debating about whether this should be at the top of the bottom. the data part is what is NEW for histograms compared to basic plots. so that could be justification to add this to the BOTTOM in a section that says somethign like:

"You can also test plot x and y axes, and titles on histograms...   

<or something like that> this is really great. thank you so much for pulling this together @ryla5068

**Comment by lwasser** [comment]
also all of CI is broke here. i'll go back to your other PR first to see if it has to do with something over there!

**Review by lwasser — CHANGES_REQUESTED** [review]
Ok please update this from master @ryla5068 and then add a section on testing for titles and such on histograms at the bottom of the vignette. then this will be ready to merge!! i'm assuming CI will be happy when you update from master but i'll have a quick look at this next.

**Comment by lwasser** [comment]
hey @ryla5068 looks like there are still some merge conflicts on this PR. can you please have a look, clean this up so I can review and merge?

**Comment by marty-larocque** [comment]
@lwasser This should be done. Your changes yesterday resolved the merge conflicts. I made a small change (removed an erroneous import). Appveyor is failing; I can't make sense of the error, so I'm going to assume it's an issue with the CI config. Codacy has some issues with the formatting of the changelog - should I ignore this? Or are there some changes I should make?

If you have any more changes for me to make let me know.

**Comment by lwasser** [comment]
thanks @ryla5068 !! i have a look at CI to try to figure out what is going on. i think i need to turn off the changelog in the codacy checks!! i'll work on that when i look at this PR - likely friday!

**Comment by lwasser** [comment]
ok @ryla5068 appveyor is happy now. i'll merge this either tonight or tomorrow. THANK YOU for the submission! i'm working on codacy settings ... we can ignore it for now but will look more closely in the future once the settings are all straight!

**Pull request merged**
