### PR TITLE
[WIP] Adding tests: base and raster

### PR DESCRIPTION
**Pull request by kysolvik**
Opening a PR as I work on adding some more tests.

Also, I was having issues with the precommit hook which used python3.6. I changed it to 3.7 to match the environment.yml file, but this could be undone. That's in commit 9d58835aabc576f568e11f93f14acdf9dc0408e2

### CODE REVIEW

**Comment by lwasser** [comment]
thank you for this pr @kysolvik !!! please label your PR as a [WIP] work in progress so i know it's under development. when you are ready for a review, please remove WIP from the name and ping me to provide a review. I suggest that we organize sets of tests in separate branches. so perhaps this PR only covers test for base and raster. 

Then we have a tests_vector etc for other tests. that way when you are done writing tests for a module (or a set of methods) the review process moves along more quickly. WHen PR's get too big they become challenging to review and accept.

**Comment by kysolvik** [comment]
hey @lwasser, sounds great! Sorry about that, thanks for the suggestion. I updated the name, I'll let you know when it's ready!

**Comment by lwasser** [comment]
oh please don't apologize @kysolvik we didn't talk about a workflow. but it's good if we work on one thing at a time just so i know what you are working on. Also i think appveyor is working so i'll likely merge that PR today or monday  so we have windows testing too!! yahoo!

thank you again for this. it's great to have another set of eyes on this package!!

**Comment by kysolvik** [comment]
Closing, will split into multiple PRs

**Pull request closed without merging**
